apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2alpine-deployment
  labels:
    app: alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
      - name: alpine1
        image: alpine
        command: ['sh', '-c', 'echo En Marcha alpine 1; sleep 1000']
        volumeMounts:
          - name: alpine-shared
            mountPath: /shared1
        env:
          - name: usuariodb   # Variable de entorno que recogera el valor de la key: usuario
            valueFrom:
              configMapKeyRef:
               name: miconfiguracion1
               key: usuario
          - name: ip          # Variable de entorno que recogera el valor de la key: ip
            valueFrom: 
              configMapKeyRef:
                name: miconfiguracion1
                key: ip
          - name: mariadbuser  # Lee secret de mariadb-secrets (creda por linea de comandos)
            valueFrom:
              secretKeyRef:
                name: mariadb-secrets
                key: usuario
          - name: mariadbpassword  # Lee secret de mariadb-secrets (creda por linea de comandos)
            valueFrom:
              secretKeyRef:
                name: mariadb-secrets
                key: password
      - name: alpine2
        image: alpine
        command: ['sh', '-c', 'echo En Marcha alpine 2; sleep 1000']
        volumeMounts:
          - name: alpine-shared
            mountPath: /shared2
          - name: config
            mountPath: /config
          - name: usuarios
            mountPath: /usuarios_secretos
            readOnly: true
      volumes:
        - name: alpine-shared
          hostPath:
            path: /shared
            type: DirectoryOrCreate  
        - name: config
          configMap:
            name: miconfiguracion2
        - name: usuarios
          secret:
              secretName: mysecrets